name: pytorch_v1.12.1a
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - cachetools==5.3.0
      - colour-demosaicing==0.2.3
      - colour-science==0.4.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - dominate==2.8.0
      - einops==0.6.0
      - exceptiongroup==1.1.1
      - execnet==1.9.0
      - filelock==3.12.0
      - fonttools==4.39.3
      - ftfy==6.1.1
      - future==0.18.3
      - google-auth==2.17.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.53.0
      - h5py==3.8.0
      - huggingface-hub==0.13.4
      - imageio==2.27.0
      - imgaug==0.4.0
      - iniconfig==2.0.0
      - iqa-pytorch==0.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.4.3
      - markupsafe==2.1.2
      - mat73==0.60
      - matplotlib==3.7.1
      - networkx==3.1
      - oauthlib==3.2.2
      - openai-clip==1.0.1
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pandas==1.5.3
      - pluggy==1.0.0
      - protobuf==4.22.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyciede2000==0.0.21
      - pyiqa==0.1.6.4
      - pyparsing==3.0.9
      - pytest==7.3.1
      - pytest-xdist==3.2.1
      - python-dateutil==2.8.2
      - pytorch-msssim==0.2.1
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - regex==2023.3.23
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.20.0
      - scipy==1.10.1
      - shapely==2.0.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tifffile==2023.4.12
      - timm==0.6.13
      - tomli==2.0.1
      - torch-tb-profiler==0.4.1
      - torchinfo==1.8.0
      - tornado==6.3.2
      - tqdm==4.65.0
      - visdom==0.2.4
      - wcwidth==0.2.6
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - yapf==0.33.0
